### ISSUE TITLE
windows平台好像有错误了

### ISSUE THREAD

**Issue by currydai** [axipo/pdfTranslator#10]
(node:16984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)

**Comment by liwenjie119** [comment]
(node:2752) UnhandledPromiseRejectionWarning: Error
    at getError (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2752) UnhandledPromiseRejectionWarning: Error
    at getError (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2752) UnhandledPromiseRejectionWarning: Error
    at getError (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
(node:2752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by forMwish** [comment]
我也出错了，不过log不一样
(node:13060) UnhandledPromiseRejectionWarning: Error
    at getError (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
(node:13060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by noahzip** [comment]
C:\Users\d\Desktop\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:83
    var e = new Error(msg);
            ^

Error
    at getError (C:\Users\d\Desktop\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (C:\Users\d\Desktop\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:124:24)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'API_SERVER_ERROR'
}

**Comment by zl1n** [comment]
(node:97309) UnhandledPromiseRejectionWarning: Error
    at getError (/pdfTranslator/node_modules/translation.js/dist/tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (/pdfTranslator/node_modules/translation.js/dist/tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:97309) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:97309) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yaxin-l** [comment]
“(node:7324) UnhandledPromiseRejectionWarning: Error
    at getError (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (E:\snapshot\pdfTranslator\node_modules\translation.js\dist\tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
(node:7324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.” 我得到了这个报错~
