### ISSUE TITLE
linux无法使用该软件

### ISSUE THREAD

**Issue by hero-y** [axipo/pdfTranslator#5]
你好，我在解压好pdfTranslator-linux-x64.tar.gz之后，双击运行其中的软件时，没有出现任何反应，是什么原因呢？我的ubuntu是16.0.4。谢谢！

**Comment by w2obin** [comment]
我也遇到了这样的问题 我是deepin

**Comment by chgwan** [comment]
用命令行运行然后查看报错

**Comment by Youjiangbaba** [comment]
app listening on port 3000!
程序将自动打开浏览器，注意：目前仅仅测试了chrome，请尽量使用基于chrome的浏览器
如果您的默认浏览器是ie，可以复制网址到其他浏览器打开（推荐chrome）

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /snapshot/pdfTranslator/node_modules/open/xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)


您好，报错如上，请问如何解决呢？
系统为ubunt18，已安装nodejs
（
sudo apt-get install nodejs 
sudo apt-get install npm
）

**Comment by menlay** [comment]
我遇到了同样的问题，选择从源码安装运行，可以成功运行。如果node版本太低，可能会出现unexpect“{”这个错误，更新就好

**Comment by visualDust** [comment]
running into a similar issue. While running, the terminal said:
```
app listening on port 3000!
程序将自动打开浏览器，注意：目前仅仅测试了chrome，请尽量使用基于chrome的浏览器
如果您的默认浏览器是ie，可以复制网址到其他浏览器打开（推荐chrome）

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /snapshot/pdfTranslator/node_modules/open/xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)
```
I've got my nodejs and npm up-to-date. It works if you build from the source, but the binary file doesn't work anyway.
